telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\telegram\ext\dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "C:\Python34\lib\site-packages\telegram\ext\commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "E:\Projects\gitTestProbe\part_2\bot_2.py", line 18, in calc
    num_2 = float(phrase[3])
ValueError: could not convert string to float: '+'
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\telegram\ext\dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "C:\Python34\lib\site-packages\telegram\ext\commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "E:\Projects\gitTestProbe\part_2\bot_2.py", line 18, in calc
    num_2 = float(phrase[3])
ValueError: could not convert string to float: '+'
telegram.ext.updater - ERROR - Error while getting Updates: Timed out
telegram.ext.updater - WARNING - Exiting immediately!
